- name: Run API tests (main)
  run: |
    mkdir -p reports
    newman run postman/nasa-openapis-fixed.postman_collection.json \
      -e postman/nasa-env.postman_environment.json \
      --env-var "baseUrl=https://api.nasa.gov" \
      --env-var "api_key=${{ secrets.NASA_API_KEY }}" \
      --reporters cli,htmlextra \
      --reporter-htmlextra-export reports/newman.html

- name: Run API tests (extras)
  run: |
    newman run postman/nasa-extras.postman_collection.json \
      -e postman/nasa-env.postman_environment.json \
      --env-var "baseUrl=https://api.nasa.gov" \
      --env-var "api_key=${{ secrets.NASA_API_KEY }}" \
      --reporters cli,htmlextra \
      --reporter-htmlextra-export reports/newman-extras.html

- name: Upload reports
  uses: actions/upload-artifact@v4
  with:
    name: newman-reports
    path: |
      reports/newman.html
      reports/newman-extras.html

