name: API tests (Newman)

on:
  push:
  pull_request:
  workflow_dispatch:   # allow manual runs
  schedule:
    - cron: "0 6 * * *"   # optional: daily 06:00 UTC

jobs:
  newman:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Newman
        run: |
          npm i -g newman newman-reporter-htmlextra

      - name: Run API tests
        run: |
          mkdir -p reports
          newman run postman/nasa-openapis.postman_collection.json \
            -e postman/nasa-env.postman_environment.json \
            --env-var "baseUrl=https://api.nasa.gov" \
            --env-var "api_key=${{ secrets.NASA_API_KEY }}" \
            --reporters cli,htmlextra \
            --reporter-htmlextra-export reports/newman.html

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: reports/newman.html
          if-no-files-found: error
