name: API tests (All Collections)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  newman:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Newman
        run: npm i -g newman newman-reporter-htmlextra

      - name: Run all Postman collections
        run: |
          set -e
          mkdir -p reports

          # List your collections here (edit paths if your filenames differ)
          collections=(
            "postman/nasa-openapis-fixed.postman_collection.json"
            "postman/nasa-extras.postman_collection.json"
            "postman/nasa-donki-extras.postman_collection.json"
          )

          for c in "${collections[@]}"; do
            if [ -f "$c" ]; then
              echo "=== Running $c ==="
              BASENAME=$(basename "$c" .postman_collection.json)
              newman run "$c" \
                -e postman/nasa-env.postman_environment.json \
                --env-var "baseUrl=https://api.nasa.gov" \
                --env-var "api_key=${{ secrets.NASA_API_KEY }}" \
                --reporters cli,htmlextra \
                --reporter-htmlextra-export "reports/${BASENAME}.html"
            else
              echo "::warning title=Missing collection::File not found: $c"
            fi
          done

      - name: Upload all HTML reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: newman-reports
          path: reports/*.html
          if-no-files-found: warn
